### ISSUE TITLE
should this project provide allowed globals, or rules about them?

### ISSUE THREAD

**Issue by nebulousdog** [lo1tuma/eslint-plugin-mocha#178]
instead of providing globals in `.eslintrc.yml`, should this project provide globals or rules about globals?

For example, I assume many of us have something like the following in our `.eslintrc.yml` file:

```
globals:
  expect: true

  after: true
  afterEach: true
  before: true
  beforeEach: true

  context: true
  describe: true
  it: true

  chai: true
  sinon: true
```
